spring:
  profiles: local
  message: Hello Spring MemberService Local Server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true  
management:
  endpoints:
    web:
      exposure:
        include: info, refresh
